### ISSUE TITLE
chat spam (and system log spam)

### ISSUE THREAD

**Issue by CSTufts** [MinecraftPhi/MinecraftPhi-modules#12] opened 2019-08-10 12:37 UTC
I installed this as someone said they had it as a dependency, now every tick there is a message from each of the entities that were created stating that they didn't do anything

[@: Executed 0 commands from 0 functions]

(making my world almost unusable...)
how do I fix it?
thanks

**Comment by vdvman1** [comment] 2019-08-10 12:40
Run these two commands, which should disable that message. It is not a problem with Phi, it just means you are op and that there is a command block running (which Phu has one of in each dimension):
gamerule logAdminCommands false
gamerule commandBlockOutput false

**Comment by maicol07** [comment] 2020-06-26 16:19
I can confirm this is happening at the moment. Can you fix it?

**Comment by vdvman1** [comment] 2020-06-27 13:09
Please read my previous comment in this issue for the explanation and fix. It is not a bug

**Comment by maicol07** [comment] 2020-06-27 13:14
@vdvman1 that fix didn't work

**Comment by vdvman1** [comment] 2020-06-28 05:50
What version are you playing in? And are you using any mods/plugins?

**Comment by maicol07** [comment] 2020-06-28 07:25
@vdvman1 1.16.1 with any mods  
EDIT: Singleplayer and standard server world accepts `commandBlockOutput` to false, while Bukkit/Spigot/Paper don't change the setting

**Comment by maicol07** [comment] 2020-06-28 11:06
Fixed with `/gamerule sendCommandFeedback false`

**Comment by maicol07** [comment] 2020-06-28 11:12
Actually, I've found the source of this bug. Every time the datapack reloads it resets the `sendCommandFeedback` rule to `true`

**Comment by vdvman1** [comment] 2020-06-28 11:18
Where do you see it resetting that gamerule? I just did a search on the entire source code and the `gamerule` command is never run

**Comment by maicol07** [comment] 2020-06-28 11:20
@vdvman1 I've tried in game disabling and enabling the ~Bonsai Pots datapack from Blue commander~ [Builder's Wands](https://www.planetminecraft.com/data-pack/builder-s-wands/) datapack that uses Phi  
**UPDATE**: The correct datapack is Builder's Wands

**Comment by maicol07** [comment] 2020-06-28 12:20
However, this can't be classified as a fix because it deletes some command features. Also, the commands continues to execute even when the pack is disabled

**Comment by vdvman1** [comment] 2020-06-28 12:23
That pack sets it back to `false`, it doesn't set it to `true`, so you shouldn't be getting the spam
And the commands can't be stopped, they are there for any datapack to be able to run logic from the command block update portion of the tick

**Comment by maicol07** [comment] 2020-06-28 12:25
@vdvman1 maybe it should be disabled if there isn't any pack that uses Phi... or at least hiding them...

**Comment by vdvman1** [comment] 2020-06-28 12:27
The messages should only show to OPs, and doing the commands I suggested should have stopped the message anyway, it is probable that whatever mods you had installed (including mod/plugin loaders) could have been messing with it

**Comment by vdvman1** [comment] 2020-06-28 12:28
In my test world in vanilla I don't get any spamming at all, and I have `gamerule sendCommandFeedback true`, so that tells me that that gamerule is not the one that needs to be disabled to fix it in vanilla

**Comment by maicol07** [comment] 2020-06-28 12:32
@vdvman1 that's right. The issue is that Spigot doesn't set that command to false even if it's set

**Comment by vdvman1** [comment] 2020-06-28 12:35
Yeah, so this isn't a bug with Phi or builders wands, it is a bug with Spigot.
You will find the same problem happens with any command block, not just the 3 in Phi

**Closed as completed** 2020-07-01 04:47 UTC
